version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tripplanner-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TripPlanner@123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tripplanner-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  sqlserver_data: